version: '3.8'

services:
  frontend:
    build: ./iota-frontend
    ports:
      - '5173:5173'
    volumes:
      - ./iota-frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build: ./iota-backend
    ports:
      - '3000:3000'
    volumes:
      - ./iota-backend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - db
      - minio

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: iota
      MYSQL_USER: iota_user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - iota_network

  minio:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - '9000:9000'
    volumes:
      - minio_data:/data
    networks:
      - iota_network

networks:
  iota_network:
    driver: bridge

volumes:
  db_data:
  minio_data:
