version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: iota_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: iota
      MYSQL_USER: iota_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - iota_network

  minio:
    image: quay.io/minio/minio:latest
    container_name: iota_minio
    command: server --console-address ":9090" /data
    ports:
      - "9000:9000"
      - "9090:9090"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    networks:
      - iota_network

  frontend:
    build: ./iota-frontend
    ports:
      - '5173:5173'
    volumes:
      - ./iota-frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - iota_network

  backend:
    build: ./iota-backend
    ports:
      - '3000:3000'
    volumes:
      - ./iota-backend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - db
      - minio
    networks:
      - iota_network

networks:
  iota_network:
    driver: bridge

volumes:
  db_data:
    driver: local
  minio_data:
    driver: local
